/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 public/cupncookie.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cupncookie.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Circle003.geometry} material={materials.Cookie} position={[4.532, 0.704, 0.453]} scale={2.757}>
        <mesh geometry={nodes.Cube.geometry} material={materials.Choco} position={[-0.542, 0.062, 0.078]} scale={0.276} />
        <mesh geometry={nodes.Cube001.geometry} material={materials.Choco} position={[-0.641, 0.314, -0.208]} scale={0.199} />
        <mesh geometry={nodes.Cube002.geometry} material={materials.Choco} position={[0.083, 0.406, -0.473]} scale={0.173} />
        <mesh geometry={nodes.Cube003.geometry} material={materials.Choco} position={[0.425, 0.337, -0.428]} scale={0.176} />
        <mesh geometry={nodes.Cube004.geometry} material={materials.Choco} position={[-0.686, 0.28, 0.161]} rotation={[-0.117, 0.429, 0.757]} scale={0.162} />
        <mesh geometry={nodes.Cube005.geometry} material={materials.Choco} position={[-0.468, 0.378, 0.017]} scale={0.176} />
        <mesh geometry={nodes.Cube006.geometry} material={materials.Choco} position={[-0.355, 0.352, -0.533]} scale={0.171} />
        <mesh geometry={nodes.Cube007.geometry} material={materials.Choco} position={[0.118, 0.437, -0.049]} scale={0.173} />
        <mesh geometry={nodes.Cube008.geometry} material={materials.Choco} position={[-0.258, 0.297, 0.512]} rotation={[-0.318, 0.577, 1.222]} scale={0.172} />
        <mesh geometry={nodes.Cube009.geometry} material={materials.Choco} position={[-0.403, 0.213, 0.588]} rotation={[-1.075, 0.309, 2.861]} scale={0.161} />
        <mesh geometry={nodes.Cube010.geometry} material={materials.Choco} position={[0.413, 0.366, 0.057]} rotation={[-0.078, 0.373, 0.636]} scale={0.187} />
        <mesh geometry={nodes.Cube011.geometry} material={materials.Choco} position={[-0.205, 0.444, 0.049]} rotation={[-0.184, 0.496, 0.93]} scale={-0.14} />
        <mesh geometry={nodes.Cube012.geometry} material={materials.Choco} position={[0.232, 0.375, 0.375]} rotation={[-0.032, 0.279, 0.457]} scale={0.128} />
        <mesh geometry={nodes.Cube013.geometry} material={materials.Choco} position={[-0.134, 0.431, -0.267]} scale={0.151} />
        <mesh geometry={nodes.Cube014.geometry} material={materials.Choco} position={[0.023, 0.343, 0.481]} scale={0.178} />
        <mesh geometry={nodes.Cube015.geometry} material={materials.Choco} position={[-0.031, 0.301, -0.69]} rotation={[-0.085, -0.247, -0.431]} scale={0.204} />
        <mesh geometry={nodes.Cube016.geometry} material={materials.Choco} position={[0.083, 0.406, -0.473]} scale={0.184} />
        <mesh geometry={nodes.Cube017.geometry} material={materials.Choco} position={[0.258, 0.235, 0.674]} scale={0.144} />
        <mesh geometry={nodes.Cube018.geometry} material={materials.Choco} position={[-0.121, 0.399, 0.228]} scale={0.144} />
        <mesh geometry={nodes.Cube019.geometry} material={materials.Choco} position={[-0.079, 0.211, 0.673]} rotation={[-1.075, 0.309, 2.861]} scale={0.177} />
        <mesh geometry={nodes.Cube020.geometry} material={materials.Choco} position={[-0.434, 0.333, 0.38]} rotation={[-1.075, 0.309, 2.861]} scale={0.131} />
        <mesh geometry={nodes.Cube021.geometry} material={materials.Choco} position={[0.427, 0.33, 0.507]} rotation={[-1.075, 0.309, 2.861]} scale={0.161} />
        <mesh geometry={nodes.Cube022.geometry} material={materials.Choco} position={[0.765, 0.23, -0.105]} scale={0.173} />
      </mesh>
      <mesh geometry={nodes.Circle004.geometry} material={materials['Cookie.001']} position={[1.34, 0.058, 3.08]} scale={1.826} />
      <mesh geometry={nodes.Circle001.geometry} material={materials['Cookie.001']} position={[-0.544, 0.8, 3.848]} rotation={[-2.776, 0.813, 2.583]} scale={1.688} />
      <mesh geometry={nodes.Circle005.geometry} material={nodes.Circle005.material} position={[-0.02, 0.033, 0.12]} scale={1.193} />
      <mesh geometry={nodes.Circle012.geometry} material={materials.coffee} position={[-1.867, 0.483, -1.629]} rotation={[0, 0.55, 0]} scale={1.383}>
        <mesh geometry={nodes.Circle013.geometry} material={materials.White} position={[0.293, -0.468, -0.31]} scale={[1.288, 1.288, 1.372]} />
        <mesh geometry={nodes.Circle014.geometry} material={materials.White} position={[0.021, -0.69, 0.06]} scale={1.288} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/cupncookie.glb')
